[package]
name = "knotty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
insta = "1.21.0"
pretty_assertions = "1.3.0"

[dependencies]
itertools = "0.10.5"
